### ISSUE TITLE
Error en DoctrineVideoRepository.php

### ISSUE THREAD

**Issue by frannixo95** [vics80/ddd-videolibrary-tutorial#1]
Buenas, como parte del último video falta explicar como mostrar los subtitle ya que da error en el toDomain de DoctrineVideoRepository.php por que le falta pasar un SubtitleCollection

**Comment by diegoinaui** [comment]
Hola, yo lo que hice para corregirlo es

**Comment by diegoinaui** [comment]
public function toDomain(VideoEntity $videoEntity): Video
  {
    return new Video(
      new VideoId($videoEntity->id()),
      $videoEntity->title(),
      $videoEntity->duration(),
      new VideoStatus($videoEntity->status()),
      $this->subtitlesToDomain($videoEntity->subtitles()),
      $videoEntity->createdAt(),
      $videoEntity->updatedAt()
    );
  }

  private function subtitlesToDomain($subtitles): SubtitleCollection
  {
    return new SubtitleCollection(
      array_map(function (SubtitleEntity $subtitleEntity) {
        return $this->subtitleToDomain($subtitleEntity);
      }, $subtitles->getValues())
    );
  }

**Comment by vics80** [comment]
Disculpad la demora en contestar.

La respuesta de diegoinaui es buena.

De todos modos en is nuesvos proyectos estoy suprimiendo los toDomain y toInfrastructure de los Repository. Estoy poniendo esas funciones en cada entidad.

Por ejemplo el toInfrastructure de VideoRepository lo sustituyo por una static function en la entidad Video:

```
public static functio fromDomain(VideoDomain $video): self
{
     return new self(
          $video->id()->value(),
          $video->title(),
          ...
     );
}
```

el toDomain de VideoRepository lo sustituyo por una función en la entidad Video:

```
public function toDomain(): VideoDomain
{
      return new VideoDomain(
            new VideoId($this->id),
            $this->titile,
            ...
      );
}
```
